### ISSUE TITLE
Untrasnlated strings in some YaST2 components

### ISSUE THREAD

**Issue by ivanvorstanenko** [yast/yast-translations#32]
Hello!
There are some untranslated strings in YaST2, but in this repository translations exist.
For example, in [yast-control](https://l10n.opensuse.org/translate/yast-control/master/ru/?checksum=8daf719bf27b3a9&sort_by=-priority,position) and in[ yast-installation](https://l10n.opensuse.org/projects/yast-installation/master/#alerts).

So, when I try to install Tumbleweed, already translated strings don't translate.

Maybe, due to wrong link in Webplate transtlation panel?

P. S. I created bug reports in [Leap](https://bugzilla.opensuse.org/show_bug.cgi?id=1197965) and [Tumbleweed](https://bugzilla.opensuse.org/show_bug.cgi?id=1197982) sections (there is screenshot), but last openned issues weren't answered long time, so, I afraid of not being heard.

**Comment by stanislav-brabec** [comment]
None of reported problems come from yast-translations. It is a problem of the yast gettext extraction or even ruby-gettext. Please follow referred bugs for the progress.

The referred alert of the yast-installation was reported as a new bug [services-manager uses two translation domains for no reason](https://bugzilla.suse.com/show_bug.cgi?id=1198263).
